version: "3"
services:
  app:
    extends:
      file: ./local-data/docker-compose.yaml
      service: app
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
volumes:
  docker_data: