version: "3"
services:
  app:
    cpus: 4
    mem_limit: 8g
    build:
      context: ../..
      dockerfile: ./.devcontainer/Dockerfile
    extra_hosts:
      - fakeservices.datajoint.io:127.0.0.1
    volumes:
      - ../../..:/workspaces
    privileged: true # only because of dind